#!/usr/bin/env python3
import sys
import os

# Add the parent directory (project root) to sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from code_sushi.main import main

if __name__ == "__main__":
    main()
